[versions]
agp = "8.13.1"
kotlin = "2.0.21"

[libraries]

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
